#!/bin/bash

# sysinfo_page - A script to produce a system information HTML file
# using shell functions

##### Constants
TITLE="System Information for $HOSTNAME"
RIGHT_NOW="$(date +"%x %r %Z")"
TIME_STAMP="Updated on $RIGHT_NOW by $USER"

##### Functions
system_info()
{
  # Temporary function stub
  echo "<h2>System release info</h2>"
  echo "<p>Function not yet implemented</p>"
}

show_uptime()
{
  # Function will display the output of the uptime command
  echo "<h2>System uptime</h2>"
  echo "<pre>"
  uptime
  echo "</pre>"
}

drive_space()
{
  # Function provides a summary of the space used by all mounted file systems
  echo "<h2>File system space</h2>"
  echo "<pre>"
  df
  echo "</pre>"
}

function home_space()
{
  # Function will display the amount of space each user is using in
  # their home directory
  # only the superuser can get this information
  if [ "$(id -u)" = "0" ]; then
    echo "<h2>Home directory space by user</h2>"
    echo "<pre>"
    echo "Bytes Directory"
    du -s /home/* | sort -nr
    echo "</pre>"
  fi 
} # end of home_space

##### Main
cat <<- _EOF_
    <html>
    <head>
        <title>$TITLE</title>
    </head>

    <body>
        <h1>$TITLE</h1>
        <p>$TIME_STAMP</p>
        $(system_info)
        $(show_uptime)
        $(drive_space)
        $(home_space)
    </body>
    </html>
_EOF_
