#!/bin/bash

# sysinfo_page - A script to produce an HTML file
# improvement of 1-sysinfo_page: a here script

cat << _EOF_
<html>
<head>
    <title>
    The title of your page
    </title>
</head>

<body>
    Your page content goes here
</body>
</html>
_EOF_
